apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: computer-academy
  namespace: computer-academy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computer-academy
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 60}
      - setWeight: 40
      - pause: {duration: 60}
      - setWeight: 60
      - pause: {duration: 60}
      - setWeight: 80
      - pause: {duration: 60}
      - setWeight: 100
  template:
    metadata:
      labels:
        app: computer-academy
    spec:
      containers:
      - name: computer-academy
        image: ketanmahajan24/computer-academy-webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
