apiVersion: v1
kind: Service
metadata:
  name: computer-academy-service
  namespace: computer-academy
spec:
  selector:
    app: computer-academy
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30115     
  type: NodePort         
